In [3]:
import numpy as np
import pandas as pd

arr = np.array([10,20,60,80,100]);
arr

array([ 10,  20,  60,  80, 100])

In [5]:

matrix = np.array([[10,20],[60,80]]);
matrix

array([[10, 20],
       [60, 80]])

In [7]:
 arr*2

array([ 20,  40, 120, 160, 200])

In [8]:
np.mean(arr)

np.float64(54.0)

In [16]:
data  = {
    'Name' : ['Ram', 'Shyam', 'Mohan', 'Sohan'],
    'Gender': ['Male','Female','Female', 'Male'],
    'Score': [100,50,20,60]
}

df = pd.DataFrame(data)
print(df)



    Name  Gender  Score
0    Ram    Male    100
1  Shyam  Female     50
2  Mohan             20
3  Sohan    Male     60


In [11]:
print(df['Name'])

0      Ram
1    Shyam
2    Mohan
3    Sohan
Name: Name, dtype: object


In [17]:
print(df['Score'].mean())

57.5


In [18]:
print(df.describe()) # Summary

            Score
count    4.000000
mean    57.500000
std     33.040379
min     20.000000
25%     42.500000
50%     55.000000
75%     70.000000
max    100.000000


print(df.head())

In [19]:
df.head()

Name  Gender  Score
0    Ram    Male    100
1  Shyam  Female     50
2  Mohan             20
3  Sohan    Male     60

In [21]:
df.tail(2)

Name Gender  Score
2  Mohan            20
3  Sohan   Male     60

In [22]:
df['Score'].sum()

np.int64(230)

In [25]:
df['Score'].min()


np.int64(20)

In [26]:

df['Score'].max()

np.int64(100)

In [27]:
df['Score'].std()

np.float64(33.04037933599835)

In [28]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    4 non-null      object
 1   Gender  4 non-null      object
 2   Score   4 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes


In [29]:
df.shape

(4, 3)

In [31]:
df.columns


Index(['Name', 'Gender', 'Score'], dtype='object')

In [32]:
df.dtypes

Name      object
Gender    object
Score      int64
dtype: object